### ISSUE TITLE
configure formula part of sheet

### ISSUE THREAD

**Issue by dienstruilamstelveen** [clyall/FormEmailer#1]
Hi.
Ik keep getting this: **Error: Invalid sheet for Formulierreacties1!L:M. Your data was not saved.**
In previous version it was advised to skip 1 column (keep it empty), i tried it with and without an empty column, but no succes.

![problem formemailer](https://user-images.githubusercontent.com/49573530/56069286-9ea11800-5d82-11e9-9e76-1691dcee2f89.png)

**Comment by clyall** [comment]
Hi,

Could you paste your config (FormEmailer!B3) please?

**Comment by clyall** [comment]
Also please paste a screenshot on the entire sheet, including the tab with the name of the sheet at the bottom

**Comment by dienstruilamstelveen** [comment]
I can share the sheet with you.
So you can see everything

Aland

Op za 13 apr. 2019 02:17 schreef clyall <notifications@github.com>:

**Comment by dienstruilamstelveen** [comment]
Yes i will,

Aland

Op za 13 apr. 2019 02:17 schreef clyall <notifications@github.com>:

**Comment by clyall** [comment]
Sharing it is perfect, I'll take a look when it comes through

**Comment by clyall** [comment]
This bug is now fixed; if anyone else is experiencing this issue during the initial beta, please email me for an updated and fixed file
