### ISSUE TITLE
Bcc field does not save

### ISSUE THREAD

**Issue by Sportcat** [clyall/FormEmailer#10]
I've entered my email in the Bcc field and saved the settings. but it does not save, or bcc me when a submission is entered.

When I go back into settings the Bcc field is empty. It is also highlighted in blue for some reason.

**Comment by clyall** [comment]
Would you mind sharing your spreadsheet with me so I can take a look?

cole.lyall@gmail.com

**Comment by clyall** [comment]
It looks like there was a bug with the BCC field. I fixed it in your sheet and it should work now.

For anyone else experiencing this bug, please re-comment on this issue and I can get it fixed for you. This will also be fixed in the next version release (4.1)

**Comment by Sportcat** [comment]
Thank you. Is it possible to make the settings window larger when editing?

**Comment by clyall** [comment]
Unfortunately, Google's new UI framework does not let you resize the settings window.

If you need to edit the HTML body, I would suggest using a separate HTML editor and pasting it into the settings when you are done

**Comment by JDG-HK** [comment]
Hi Cole,

Nice work BTW!!

I have the same issue, unfortunately not allowed to share the spreadsheet, how are you fixing this, by editing B3 cell? Or fixing in the code?

J

**Comment by clyall** [comment]
Hi there,

In settings.html, change line 102 from:

`id="<?= 'sender-name' + i ?>"`

to: 

`id="<?= 'bcc' + i ?>"`

Late night typo on my part ;)
