### ISSUE TITLE
Body HTML checkbox - always checked?

### ISSUE THREAD

**Issue by asalerno1964** [clyall/FormEmailer#12]
I have FormEmailer configured to send 2 emails.  (THANK YOU again for making the new version, well done!)

If I uncheck the "Body: html" checkbox on either (or both) Email1 or Email2, every time I go back into settings, the little "html" box is checked again.

Could just be me, maybe I setup something wrong.  But the form is sending emails, so I got that much right.

Thanks

**Comment by clyall** [comment]
This is a bug -- if you share your sheet with me I can fix it for you

cole.lyall@gmail.com

**Comment by asalerno1964** [comment]
Shared, Thank you very much.

**Comment by clyall** [comment]
This should be working now in the sheet you shared with me

If anyone else has this issue (and Version 4.1 is still not released), open settings.html and change line 308 from:

`json['html' + currentTab] = $('#html' + currentTab).val() || ''`

to: 

`json['html' + currentTab] = $('#html' + currentTab).is(":checked") ? 'on' : ''`

**Comment by JDG-HK** [comment]
I had this too, fix works perfectly
