### ISSUE TITLE
Email Sending Twice

### ISSUE THREAD

**Issue by chrisdog678** [clyall/FormEmailer#14]
Email is sending twice on responses. The trigger is set only to send once currently on form emailer.

**Comment by chrisdog678** [comment]
I know a few others have had the same issue. Cannot link my file due to work related material in it unfortunately. Hopefully some others can.

**Comment by clyall** [comment]
Hi Chris,

Could you copy / paste the contents of your B3 cell? (Should be the config cell on FormEmailer sheet)

It is only your config, and shouldn't reveal any sensitive data

**Comment by chrisdog678** [comment]
{"s":{"qWarn":"150","closure":"values","replyTo0":"","qLimit":"30","to0":"#Email Address#","html0":"on","fLoc":"","sender0":"FormEmailer","subject0":"IPS -  #Candidate Name#","qtt":"1","fSheet":"Form Responses 1","body0":"                                      <b>******FSR IPS*****</b>                                                                          <b>Candidate Name: </b>#Candidate Name#<br>\n\n<hr>\n<b>[Overview]</b>\n<br>\n<br>\n\n\n<b>Motivation - what made you decide to take this call?: </b>#Motivation - what made you decide to take this call?#<br><br>\n\n<b>Please give me a 60-second overview of your background and current role: \n\n</b>#Please give me a 60-second overview of your background and current rol...#\n\n<br><br>\n\n<b>Quota History  </b>#Quota History - walk me through your quota history over the last 5 yea...#<br><br>\n<b>Context for any job hoppiness : </b>#Context for any job hoppiness (if candidate has been in any roles less...#<br><br>\n\n<hr>\n<b>Market Knowledge</b>\n<br>\n<br>\n\n\n<b>What is a multi cloud strategy? Can you give me an example?: </b>#What is a multi cloud strategy? Can you give me an example?#<br><br>\n<b>Who do you think are the main buyers of public cloud in a business? : </b>#Who do you think are the main buyers of public cloud in a business? Wh...#<br><br>\n<b>Tell me about a time where you sold into an account that is deeply ingrained with a competitor? What challenges did you encounter? How did you overcome them?: </b>#Tell me about a time where you sold into an account that is deeply ing...#<br>\n<br>\n<hr>\n<b>Sales Aptitude Questions</b>\n<br>\n<br>\n\n<b>What is the largest deal you closed? </b>#What is the largest deal you closed? How did you identify and approach...#<br>\n<b>Tell me about a time where you had to negotiate a complex deal with a c-level decision maker: </b>#Tell me about a time where you had to negotiate a complex deal with a ...#<br><br>\n\n<hr>\n<b>Relationship Management</b>\n<br><br>\n\n\n<b>Can you name any Top 5,000 Enterprise CIO's that would write you a reference today? Why would they give you a reference?: </b>#Can you name any Top 5,000 Enterprise CIO's that would write you a ref...#<br><br>\n<b>Can you give me an example of a “C-Level” relationship you have built?: </b>#Can you give me an example of a “C-Level” relationship you have built?...#<br>\n\n<br><hr>\n<b>Vertical</b>\n<br><br>\n\n<b>How does the way you articulate your product’s value proposition change based on the customer’s vertical? : </b>#How does the way you articulate your product’s value proposition chang...#<br>\n\n\n<br><hr>\n<b>Compensation</b>\n<br><br>\n\n<b>To make sure I’m focusing on the right level, what are your expectations: </b>#To make sure I’m focusing on the right level, what are your expectatio...#<br>\n<b>Is candidate familiar with comp model and philosophy?: </b>#Is candidate familiar with comp model and philosophy?#<br>\n\n\n<br><hr>\n<b>Process</b>\n<br><br>\n\n\n<b>Location Preference: </b>#Location Preference#<br>\n<b>Are you legally eligible to work in the US?: </b>#Are you legally eligible to work in the US?#<br>\n<b>Do you currently need, or will you someday require, Google to sponsorship: </b>#Do you currently need, or will you someday require, Google to sponsor ...#<br>\n<b>Employment History Gaps [required]: </b>\n#Employment History Gaps [required]: Can you please share details aroun...#<br>\n\n<b>Do you have any non compete or non solicits with your current employer?</b>\n<br>\n#Non Competes/Solicits#\n\n<br>\n\n<b>Leveling Rationale:</b><br>\n#Leveling Rationale#\n                                  ","bcc0":"","Version":"4","cc0":""},"T":{"sender":"Sender Name","replyTo":"Reply To","to":"To","cc":"Cc","bcc":"Bcc","subject":"Subject","body":"Body","html":"html","fSheet":"Form sheet","fSheetDESC":"Name of the sheet that holds the form answers","qtt":"Qtt Emails","qttDESC":"Max quantity of emails sent per form submitted","qWarn":"Quota warning","qWarnDESC":"Daily quota threshold that will trigger a warning email","qLimit":"Quota limit","qLimitDESC":"Quota minimum value where FormEmailer will stop sending emails","fLoc":"Formulas location","fLocDESC":"Enter the location using the format: SheetName!A:B","closure":"Closure mode","closureDESC":"What the script should do after your formulas are evaluated","closureValues":"values","closureFormulas":"formulas","closureClear":"clear","quota":"Remaining quota","quotaDESC":"Amount of your daily quota you got have now","menuSettings":"Settings","menuManually":"Process manually","menuAbout":"About","menuFix":"Fix","version":"{1} - version {2}","about1":"Script developed by {1}","about2":"Help, samples and tutorials can be found at","statusEmail":"Email{1} sent","statusNot":"Email{1} not sent","statusError":"Error sending email{1}: {2}","mailError":"Error sending email{1} on line{3}: {2}","statusQuota":"Quota limit reached","statusMissingField":"Field does not exist: {1}","statusFormattingErr":"Error formatting field: {1}","statusDateFormatErr":"Error formatting date field: {1}","manualQuestion":"Which line do you want process?\nAppend an * to the line number to process from it to the end","manualInvalid":"\"{1}\" is not a valid number. Aborting.","manual1stMult":"The first line is the n.2. I'll consider that you want to process from the beginning.","manual1stSingle":"The line number should be equal to or greater than 2.\nSince the 1st row is the header.","manualAfterLast":"The line number you typed is beyond the last one with data.","manualQuotaWarn":"Quota warning threshold reached! Continue anyway?","manualQuotaLimit":"Quota minimum limit reached\nProcess stopped at line {1}","manualSuccessMulti":"All lines from {1} to {2} processed successfully","manualSuccessSingle":"Line {1} processed successfully","manualErrors":"There were some errors on the processing, check out the rows status","yes":"Yes","no":"No","ok":"Ok","title":"{1} Settings","emailTab":"Email{1}","advTab":"Advanced","advIntro":"You don't need to worry with these settings if you don't want to.","advTip1":"*You have to '{1}' and re-open to see the updates on any changes you make here.","advTip2":"Having doubts with these parameters? Want to learn more about {1}?","advTip3":"Access the help site at","placeholders":"Answers placeholders:","addField":"Add field:","insertPlaceholder":"insert placeholder","saveAndClose":"Save and Close","sheetError":"{1} form does not exist!","numberError":"{1} is not a valid number!","formulasError":"Invalid {1}","formulasSheetError":"Invalid sheet for {1}","formulasColsError":"Invalid column reference for {1}","errorTitle":"Error","badSettings":"Your data was not saved.","versionConflict":"Config version is {1}, but script's is {2}. They are not compatible.\n","resolveConflict":"You settings version \"{1}\", is not compatible with the script's version \"{2}\". Do you want to overwrite it new default settings?","badConfig":"Your config is damaged or missing!\nDo you want to overwrite it with the default values?","badConfigCancel":"Nothing done.\nHere is the error message:\n{1}","noProblem":"There seem to be no problem with your settings.","missingSheet":"Unable to find sheet: {1}","fSheetMissing":"Your \"{1}: {2}\" cannot be found, please choose a new one and click \"{3}\" to fix","cancelMessage":"Canceled","errorReportSubject":"{1} errors report","errorReportBody":"The following errors occurred on \"{1}\" spreadsheet:\n{2}","alsoQuota":"Also, your quota is below the warning limit","quotaMailSubject":"{1} quota warning","quotaMailBody":"Your actual quota is: {1}\nIt is bellow the warning threshold: {2}","pickLanguage":"Select a language:","langIncomplete":"This language was written for an older version of the script and is probably incomplete.","pickSheet":"Select the sheet that has your form answers (or data to be merged):","install":"Configure","overwrite":"Do you confirm you want to overwrite your whole \"{1}\" sheet?","defaultBody":"Submitted values:","defaultSubject":"New form submitted","blankSheet":"Your \"{1}\" sheet is blank! Please create your form or basic data structure before installing, so the script can create nice defaults for you.","statusColumn":"{1} Status","relocateStatus":"In this new version of the script, the status column is the 1st instead of last. I have moved it for you, please verify.","statusComment":"This column must always be the first one","settingsComment":"Please do NOT modify this manually! Use the Settings interface","header":"{1}\nRunning automatically:\nYour settings are save here:","instructions":"Settings tips:\nIf you want to rename your form sheet, remember to rename the \"{1}\" parameter at the same time.\nA very good practice is to have the first row of data with some bogus values so you can make some tests before running it on the whole data set.\nThe placeholders may be used in any field, e.g. To, Subject, etc.\nThe \"#\" character is used to delimit the placeholders' boundaries, if you want to use this char in any field, write it two times \"##\". They will be replace by only one.\nYou may provide formatting instructions in the placeholder by using the \"|\" char after the field name. Take a look at the available format in the help site.\nhttps://github.com/clyall/formemailer\n\nNew install instructions:\nhttps://github.com/clyall/formemailer#time-trigger-installation","awaitingDelay":"Sending in {1} minutes"}}

**Comment by clyall** [comment]
Config looks fine... double check your time triggers and make sure you only have 1 setup for this project

**Comment by clyall** [comment]
Hi, are you still having this issue?
