### ISSUE TITLE
Getting a ReferenceError

### ISSUE THREAD

**Issue by lscombs** [clyall/FormEmailer#15]
After following Getting started directions, when I go to configure settings, I keep getting the following error:  ReferenceError: "sheetList" is not defined. This happens in both a new install and an upgrade.

**Comment by clyall** [comment]
Are you able to share your spreadsheet with me to take a look?

cole.lyall@gmail.com

**Comment by lscombs** [comment]
I figured it out. I had a bad code file for the settings code.
Thank you for getting back to me.
Laura
