### ISSUE TITLE
Question on "reply to" email

### ISSUE THREAD

**Issue by AdriannaLomas** [clyall/FormEmailer#17]
Is there a way to change the reply-to email address to the email that the user writes in the form they submit?

**Comment by clyall** [comment]
Hi Adrianna,

Yes, you can use the placeholder for that field. For example, if a user submits their email to a field called "User Email", you can use #User Email# as a placeholder for Reply-To

You can see more documentation here:
https://github.com/clyall/FormEmailer#variables-in-email-template

**Comment by AdriannaLomas** [comment]
Thank you SO much. This is exactly what I needed. 😁

Adrianna C Lomas
Student Affairs
Help Desk Supervisor
Austin Community College
phone: 512 223 7867

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail.

Please let me know how I'm doing: http://goo.gl/forms/gDxa3s3mD9
