### ISSUE TITLE
delay

### ISSUE THREAD

**Issue by dienstruilamstelveen** [clyall/FormEmailer#2]
Hi

is it possible to build in a waiting time (which delays the mail transmission) that can be activated by the content of a cell?

For example = delay (197)

I mean: No waiting time if the cell with that content does not exist in the given row or has a value of 0, but waiting time if that cell contains a value (a number in minutes)

Greetings from Uithoorn, the Netherlands

**Comment by clyall** [comment]
I think this is an interesting idea, and can probably be done.

Question: Would the "delay sending" cell apply to every row in your form sheet? This could work; if you wanted a different delay for each row, that may not be possible...

**Comment by dienstruilamstelveen** [comment]
Oops It is my intention that a user who submits a form can decide for
himself whether his response mail will be sent with a delay and also how
long that delay will be. This has a privacy background The fact that this
cannot be built in per line means that something must be found in the sheet
itself to prevent submission

Regards, Aland

Op di 23 apr. 2019 om 19:39 schreef clyall <notifications@github.com>:

**Comment by clyall** [comment]
I see, that actually is doable

I can add an advanced config setting that asks which column contains the email delay (since each row can have an independent, user-decided form value). Would that work for you?

**Comment by dienstruilamstelveen** [comment]
Yes, the most logical is the first column of the formula range, which
is always in use.
I think it should also be switchable to avoid compatibility issues
with already existing sheets


Op di 23 apr. 2019 om 23:35 schreef clyall <notifications@github.com>:

**Comment by clyall** [comment]
Great, I'll get started on this. Will keep you updated

**Comment by clyall** [comment]
I have these updates implemented. 

Do you mind if I email you the new source code so you can make sure this is what you want?

**Comment by dienstruilamstelveen** [comment]
YES, i be happy tot test it

Regards, Aland

Op wo 1 mei 2019 18:07 schreef clyall <notifications@github.com>:

**Comment by clyall** [comment]
Hi Aland,

Is the new feature working for you? I would like to publish the new version soon, and include these changes
