### ISSUE TITLE
Error after 

### ISSUE THREAD

**Issue by ericsing** [clyall/FormEmailer#20]
Hi,
There was an error message (see below) after I clicked the Install button from FormEmailer.
**No HTML file named install was found.**
How can I fix it? 
Thanks in advance :)
Eric

**Comment by clyall** [comment]
Hi Eric,

Apologies on the delay. Sounds like you did not copy over all the files. Please double check you followed the directions found here:
https://github.com/clyall/FormEmailer#getting-started
