### ISSUE TITLE
Delete Old FormEmailer

### ISSUE THREAD

**Issue by Chiurato** [clyall/FormEmailer#23]
I've moved on to FormMule so I want to delete the old FormEmailer but cannot. I've deleted the triggers but when I attempt to delete the script I get the error "Cannot delete the only open file in a project Dismiss" The uninstall instructions in Henrique Abreu old page (at the bottom) do not work.

In the G Suite Developer Hub the option for "DELETE FOREVER" is grayed out so that is not an option either.

Suggestions please?

![image](https://user-images.githubusercontent.com/52613136/60762285-c0c4d200-a021-11e9-822e-1bfd7caf7c4c.png)

![image](https://user-images.githubusercontent.com/52613136/60762286-c7ebe000-a021-11e9-8c3a-96edee189249.png)

**Comment by clyall** [comment]
Hi John,

You can just delete the contents of Code.gs, and leave a blank file there
