### ISSUE TITLE
future plans?

### ISSUE THREAD

**Issue by the-wes** [clyall/FormEmailer#24]
Is there a roadmap or any indication of expected plans for the future of FormEmailer?

Right now I'm wondering if the features from the old settings editor will come back. I especially liked the one where it would give a drop-down box of all the answers that could be inserted, with a little button to pop that answer into the message body. I think it always went at the end of the body window, which was good enough.

If the plan is to use the GitHub Issues tracker to track feature requests, please just let me know that and I will open a feature request for each individual thing I would like to see added.

Thanks.

**Comment by clyall** [comment]
Hi Wes,

My primary goal with FormEmailer was to get it running again on the new framework. As for new features, I am not too keen on adding new features at this time. I will primarily be helping solve issues with the existing version and answer questions

**Comment by clyall** [comment]
As a side note, I am open to other developers contributing to this project if they would like to add new features
