### ISSUE TITLE
ERROR: UiApp has been deprecated. Please use HtmlService instead.

### ISSUE THREAD

**Issue by ClayMorde** [clyall/FormEmailer#26]
I followed all of the instructions and then when I clicked "FormEmailer" and "install" it gave me this error: 

"UiApp has been deprecated. Please use HtmlService instead." 

Can you help me?

**Comment by clyall** [comment]
Did you also copy over the new Code.gs file?

**Comment by ClayMorde** [comment]
I have done that now.

But now there is any empty white box that says "FormEmailer Seetings"

Can you help me with this? 

Thank you very much.

**Comment by ClayMorde** [comment]
Wow. I'm doing great...

I left settings empty too. Sorry. Looks good. 

Thanks for all of these work. We appreciate it.

**Comment by clyall** [comment]
You don't have to apologize :)

Glad it's working!
