### ISSUE TITLE
Email destination with new template

### ISSUE THREAD

**Issue by whwesley** [clyall/FormEmailer#29]
Hi Cole,

First off, thank you for all the work you have done with the FormEmailer. I have this installed on many spreadsheets. My current issue is: I have installed all of the new script and I think it runs properly. The problem is on the new set up template the email destination seems like it has to be hard coded. I used to be able to select a column that housed the email from the submitted form. I need the email to be sent to the address that ends up in a specific cell from the form. Is this still possible with the new rewrite? Thanks for any help you can give.
-Bill

**Comment by jmaffei** [comment]
Hi whwesley,
    If I'm understanding the question correctly, you would just type in the "To" box the title of the question that pulls the email with # on either side.  For instance, in mine, I have the person entering the data answering the query "Teacher email".  In order to send the results to this email, in the "To" box, I type #Teacher email#.  I hope this helps and is actually answering your question.

**Comment by whwesley** [comment]
Jmaffei,
Thank you for the quick response. Your instructions worked! I tried using the (<bv>) with the # before and received the error. Thank you so much for the help.

**Comment by clyall** [comment]
Thanks Jmaffei!
