### ISSUE TITLE
No HTML file named install was found.

### ISSUE THREAD

**Issue by cynthiawen0601** [clyall/FormEmailer#3]
After I replace my form emailer from v3.65 to v4.0
A "No HTML file named install was found" error message popped out, Still can't bbypass the system and get the setting part. Did I do something wrong?

**Comment by clyall** [comment]
It sounds like you did not include the additional HTML files in your script project

Double check you followed the directions here
https://github.com/clyall/FormEmailer#getting-started

**Comment by cynthiawen0601** [comment]
You're right! thank you
