### ISSUE TITLE
Error with timeDriven vs processManually

### ISSUE THREAD

**Issue by dmgoyer** [clyall/FormEmailer#6]
I'm using the timeDriven trigger to send two emails on a form submit. The first email is sending. However, the second email does not. 

But, if I process manually after, then the second email does send. Is there a difference in the way these two functions process information??

**Comment by clyall** [comment]
Both these functions call the same internal function. Time-driven should be sending both.

Do you mind sharing your spreadsheet with cole.lyall@gmail.com so I can take a look?

**Comment by dmgoyer** [comment]
Sure, I just sent it to you.

**Comment by dmgoyer** [comment]
Hey man, we fixed it. Appreciate the support.

**Comment by clyall** [comment]
Do you mind sharing the fix?

I was looking at the spreadsheet but was not able to see the issue in the logs
