### ISSUE TITLE
Question about an Edited form submission

### ISSUE THREAD

**Issue by rdoran519** [clyall/FormEmailer#8]
Greetings Cole,
    First, thanks so much for your work on updating this, the new version works great!  I have a question to see if this is possible, and if not it's not a big deal.

Is there a way to have the FormEmailer run to send a new e-mail if the form respondent updates/edits their responses?  

From everything I can tell, the FormEmailer runs when it sees a new set of row entries in the sheet, but does not send anything if entries are changed as is done when someone edits their form responses.

I tried setting up a trigger to run onChange or onEdit, but that seemed unsuccessful.  Likewise I tried to set a trigger to "ProcessManually" when a change is seen, which works great if I make the change in the spreadsheet (however it requires me to tell it which row to process), but not when a user resubmits an edited form.

Any ideas on if this might be possible, and any suggestions on how to do so if it is?

Thanks so much!
Sincerely, 
Rob Doran

**Comment by clyall** [comment]
The "easiest" solution is to just delete the first column in their response row (FormEmailer status row / "Email Sent"). This would trigger another email to send.

Are they updating their responses in the spreadsheet, or through Google Forms?

**Comment by rdoran519** [comment]
Thanks for getting back to me so quickly!
Ah, so it is that first cell in the column that dictates whether to send or not?
In my situation, they would be updating their responses through Google Forms.  So their new responses would be sent to the sheet without my knowledge (unless they specifically told me they had update it).

**Comment by clyall** [comment]
I would have to add some event handling to catch form submit events and detect form editing vs. new submissions. 

I can work on adding this (it just may not be "soon")

**Comment by rdoran519** [comment]
I haven't worked with scripts much previously, so I don't know, but is there a script that could be run to clear out that first cell when a change is made to another cell in that same row?  If so, that could accomplish what I'm looking for as well. 

As for adding things to catch form submissions, if you think there is benefit to a lot of other people using this, then that would be great to work on eventually.  If it's just for me and it is a lot of extra work, then it may not be worth it.  I certainly didn't intend to create a lot of extra work for you, and I very much appreciate the time you've already put into this.

I can make things work as is by adding myself to the Google Form notifications, and when I see an updated submission come through I'll go in and manually process that row (or clear out that first cell).  It doesn't happen enough to be a major problem. 

Thanks!
Rob

**Comment by clyall** [comment]
Yes, your first paragraph is essentially what needs to be implemented

I'll let you know when the feature is in

**Comment by rdoran519** [comment]
Ah, gotcha.  No problem, there is no rush, and thanks again for your help.

**Comment by jac68** [comment]
Thank you Henrique and Cole for this useful script.


This is a suggestion related to this issue:    to include the edit form response link,  in the email sent.


Here is the code to calculate the link for ALL rows:
https://gist.github.com/pierandrea/3fcccada803ca34c9e09
https://docs.google.com/document/d/1m9V_AHZdA24pUAR1xGxQNt_y3k7J9RKoSG5v_9oFvcU/edit 


If a similar code is in a g.sheet   custom function,   this formula could be copied down by FormEmailer, and the edit link could be added to the email sent.


I hope you also like this idea.

**Comment by clyall** [comment]
I am not very keen to add too many more features at this time. Feel free to modify the script and implement this yourself

**Comment by rdoran519** [comment]
Thanks for the suggestion jac68, I'll take a look at those when I get a chance.  I don't know if that quite accomplishes what I'm looking for, but it could be a start.  Thanks for sharing that info.

Cole, no worries, I know anytime new code is implemented it runs the risk of causing other issues elsewhere, and I don't think my issue is one shared by many others.  Thanks for the time you've already put in, and again for keeping this great add-on working.
