### ISSUE TITLE
Code not working. Probably user error

### ISSUE THREAD

**Issue by Sportcat** [clyall/FormEmailer#9]
I made the new files in the Script editor. Copied them over and saved them.

Refreshed spreadsheet and FormEmailer menu did not appear.

What did I probably do wrong?

**Comment by clyall** [comment]
Did you resolve this issue? And if so how did you fix?

**Comment by Sportcat** [comment]
Yes... fixed it. Did not realize I also had to copy code into the existing Code.gs.

I "assumed" I only needed to create and copy into the new four .html
